export default L={
  i:undefined,
  init:(pin)=>{
    L.pin=pin
  },
  write:(w)=>{
    digitalWrite(L.pin,w);
  },
  turn:(s)=>{
    clearInterval(L.i);
    L.write(!s);
  },
  blink:(times,t=500)=>{
    clearInterval(L.i);
    L.ledOn=false;
    L.times=0;
    L.i=setInterval(()=>{
      L.write(L.ledOn);
      L.ledOn=!L.ledOn;
      L.times=L.times+1;
      if(L.times==times*2){
        L.times=0;
        clearInterval(L.i);
      }
    },(t))
  }
}
